[package]
name = "dq"
version = "0.1.0"
edition = "2024"

[features]
default = []
common-tests = []

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.60", features = ["derive"] }
duckdb = { version = "1.4.4", features = ["bundled"] }

[dev-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
