[workspace]
members = [".", "dq_test_macros", "dq_test_fixtures"]
resolver = "3"

[package]
name = "dq"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.60", features = ["derive"] }
duckdb = { version = "=1.4.4", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tempfile = "3.26.0"
terminal_size = "0.4.3"
unicode-width = "0.2.0"

[dev-dependencies]
dq_test_fixtures = { path = "dq_test_fixtures" }
dq_test_macros = { path = "dq_test_macros" }
indoc = "2.0.7"
